### GET request to example server
GET http://localhost:3000/api/v1/docs/gamecontroller/getGameByUserAndPlatform?user=rinoa&platform=PS5

### Create new user with there initial collection
POST http://localhost:3000/api/v1/docs/gamecontroller/addGamesToUserCollection
content-type: application/json

{
  "user": "rinoa",
  "game": [
    {"name": "FF16", "platform": "PS5"},
    {"name": "Stellar Blade", "platform": "PS5"}
  ]
}

### Change rating for a game
PUT http://localhost:3000/api/v1/docs/gamecontroller/updateGame
content-type: application/json

{
  "id": "66d2f1c89e8b280193705f6b",
  "gameToUpdate": "FF16",
  "keyToUpdate": "rating",
  "newValue": 5.0
}

### Change platform for a game
PUT http://localhost:3000/api/v1/docs/gamecontroller/updateGame
content-type: application/json

{
  "id": "66d2f1c89e8b280193705f6b",
  "gameToUpdate": "FF16",
  "keyToUpdate": "platform",
  "newValue": "PS5"
}

### Add an game to a users collection
POST http://localhost:3000/api/v1/docs/gamecontroller/addGameToCollection?user=rinoa
content-type: application/json

{
  "name": "Ratchet And Clank: Rift Apart",
  "platform": "PS5",
  "rating": 4.5
}

### Try to add an game to a invalid users collection
POST http://localhost:3000/api/v1/docs/gamecontroller/addGameToUserCollection?user=rinoa
content-type: application/json

{
  "name": "Octopath II",
  "platform": "PS5",
  "rating": 5.0,
  "releaseDate": "2023-02-24"
}