### GET all games for a current user
GET http://localhost:3000/api/v1/docs/gamecontroller/getAllGamesForUser?user=davidk&orderBy=ASC

### GET all games for a current user by platform
GET http://localhost:3000/api/v1/docs/gamecontroller/getAllGamesForUserByPlatform?user=davidknight&platform=PS5

### Create new user with their initial collection
POST http://localhost:3000/api/v1/docs/gamecontroller/addNewGamesToNewUser?user=user1
content-type: application/json

{
  "user": {"username": "davidk","alias": "Squall", "email": "davidknight46@hotmail.com", "isAdmin": true},
  "newGame": [{"name": "Final Fantasy 16", "platform": "PS5", "rating": 5.0,"releaseDate": "2023-06-22", "isPreOrder": true, "isInterested": false, "genre": "J_RPG", "isCompleted": true}]
}

### Add an new game to existing user
POST http://localhost:3000/api/v1/docs/gamecontroller/addAnNewGameForAnExistingUser?user=davidknight
content-type: application/json

[{
  "name": "Unicorn Overlord",
  "platform": "PS5",
  "rating": 5.0,
  "releaseDate": "2024-03-08",
  "isPreOrder": false,
  "isInterested": true,
  "genre": "RPG",
  "isCompleted": false,
  "isOwned": false
}]


### Change parameters for a game
PUT http://localhost:3000/api/v1/docs/gamecontroller/updateGameInUserCollection?user=davidknight
content-type: application/json

[
  {"id": "66d12ac2e7d3aa4dd220bdf2",
    "gameToUpdate": "Exodus",
    "keyToUpdate": "isOwned",
    "newValue": false
  },
  {
    "id": "66d12ac2e7d3aa4dd220bdf2",
    "gameToUpdate": "Stellar Blade",
    "keyToUpdate": "isOwned",
    "newValue": true
  },
  {
    "id": "66d12ac2e7d3aa4dd220bdf2",
    "gameToUpdate": "Final Fantasy 7: Rebirth",
    "keyToUpdate": "isOwned",
    "newValue": true
  },
  {
    "id": "66d12ac2e7d3aa4dd220bdf2",
    "gameToUpdate": "Final Fantasy 16",
    "keyToUpdate": "isOwned",
    "newValue": true
  },
  {
    "id": "66d12ac2e7d3aa4dd220bdf2",
    "gameToUpdate": "Nier: Automata",
    "keyToUpdate": "isOwned",
    "newValue": true
  },
  {
    "id": "66d12ac2e7d3aa4dd220bdf2",
    "gameToUpdate": "Ys VIII: Lacrimosa of Dana",
    "keyToUpdate": "isOwned",
    "newValue": true
  }
]

### Get all games that were pre-orders
GET http://localhost:3000/api/v1/docs/gamecontroller/getAllGamesIsPreOrder?isPreOrder=true&user=davidknight

### Get all games that are completed
GET http://localhost:3000/api/v1/docs/gamecontroller/getAllGamesIsCompleted?isCompleted=true&user=davidknight

### Get all games by genre
GET http://localhost:3000/api/v1/docs/gamecontroller/getAllGamesByGenre?genre=J_RPG&user=davidknight

### Get all games by genre
GET http://localhost:3000/api/v1/docs/gamecontroller/getAllGamesByGenre?genre=J_RPG&user=davidknight

### Get all games not released
GET http://localhost:3000/api/v1/docs/gamecontroller/getAllGamesNotReleased?user=davidknight

### Get all games owned
GET http://localhost:3000/api/v1/docs/gamecontroller/getAllGamesUserOwns?user=davidknight

### Remove user
DELETE http://localhost:3000/api/v1/docs/admincontroller/deleteUser?user=yangzhou
isAdmin: false
