### GET all games for a current user
GET http://localhost:3000/api/v1/docs/gamecontroller/getAllGamesForUser?user=davidknight

### GET all games for a current user by platform
GET http://localhost:3000/api/v1/docs/gamecontroller/getAllGamesForUserByPlatform?user=davidknight&platform=PS5

### Create new user with their initial collection
POST http://localhost:3000/api/v1/docs/gamecontroller/addNewGamesToNewUser?user=davidknight
content-type: application/json

[
    {"name": "Final Fantasy 16", "platform": "PS5", "rating": 5.0,"releaseDate": "2023-06-22", "isPreOrder": true, "isInterested": false, "genre": "J_RPG", "isCompleted": true},
    {"name": "Final Fantasy 7: Rebirth", "platform": "PS5", "rating": 5.0,"releaseDate": "2024-02-29", "isPreOrder": true, "isInterested": false, "genre": "J_RPG", "isCompleted": true},
    {"name": "Stellar Blade", "platform": "PS5", "rating": 4.5,"releaseDate": "2024-04-26", "isPreOrder": false, "isInterested": false, "genre": "A_RPG", "isCompleted": false},
    {"name": "Ys VIII: Lacrimosa of Dana", "platform": "PSVITA", "rating": 4,"releaseDate": "2016-07-21", "isPreOrder": false, "isInterested": false, "genre": "A_RPG", "isCompleted": false},
    {"name": "Nier: Automata", "platform": "PS4", "rating": 5.0,"releaseDate": "2017-02-23", "isPreOrder": false, "isInterested": false, "genre": "A_RPG", "isCompleted": false}
]

### Add an new game to existing user
POST http://localhost:3000/api/v1/docs/gamecontroller/addAnNewGameForAnExistingUser?user=davidknight
content-type: application/json

{
  "name": "Exodus",
  "platform": "PS5",
  "rating": 5.0,
  "releaseDate": "2099-06-22",
  "isPreOrder": false,
  "isInterested": true,
  "genre": "A_RPG",
  "isCompleted": false
}


### Change parameters for a game
PUT http://localhost:3000/api/v1/docs/gamecontroller/updateGameInUserCollection?user=davidknight
content-type: application/json

[
  {"id": "66d12ac2e7d3aa4dd220bdf2",
    "gameToUpdate": "FF8",
    "keyToUpdate": "rating",
    "newValue": 5.0
  },
  {
    "id": "66d12ac2e7d3aa4dd220bdf2",
    "gameToUpdate": "FF8",
    "keyToUpdate": "releaseDate",
    "newValue": "2019-09-03"
  },
  {
    "id": "66d12ac2e7d3aa4dd220bdf2",
    "gameToUpdate": "FF8",
    "keyToUpdate": "isPreOrder",
    "newValue": true
  },
  {
    "id": "66d12ac2e7d3aa4dd220bdf2",
    "gameToUpdate": "FF8",
    "keyToUpdate": "isInterested",
    "newValue": true
  },
  {
    "id": "66d12ac2e7d3aa4dd220bdf2",
    "gameToUpdate": "FF8",
    "keyToUpdate": "genre",
    "newValue": "J_RPG"
  }
]

### Get all games that were pre-orders
GET http://localhost:3000/api/v1/docs/gamecontroller/getAllGamesIsPreOrder?isPreOrder=true&user=davidknight

### Get all games that are completed
GET http://localhost:3000/api/v1/docs/gamecontroller/getAllGamesIsCompleted?isCompleted=true&user=davidknight

### Get all games by genre
GET http://localhost:3000/api/v1/docs/gamecontroller/getAllGamesByGenre?genre=J_RPG&user=davidknight

### Get all games by genre
GET http://localhost:3000/api/v1/docs/gamecontroller/getAllGamesByGenre?genre=J_RPG&user=davidknight